language: node_js
node_js:
- '12'
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
env:
  global:
  - GITHUB_REPO: github.com/herman7/blog.git

before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

script:
- npm run build

after_success:
- rsync -az --delete ./public/* ubuntu@118.25.172.123:/home/ubuntu/blog/

