language: node_js
node_js:
- '12'
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
env:
  global:
  - GITHUB_REPO: github.com/herman7/blog.git
script:
- vuepress build
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
